using UnityEngine;

namespace WyrmsunMapExporting
{
    public class WyrmsunMapTemplates
    {
        public static readonly string HEADER =
            "-- Stratagus Map Presentation\n-- File generated by the Stratagus v3.5.4 built-in map editor.\n\n";

        public static readonly string PLAYER_HEADER = "-- player configuration\n";

        public static readonly string TILES_MAP = "-- Tiles Map\n";

        public static readonly string DEFAULT_HEADER = "-- set map default stat and map sound for unit types\n";

        public static readonly string UNITS_HEADER =
            "-- place units\nif (MapUnitsInit ~= nil) then MapUnitsInit() end\n";

        public static string Header()
        {
            return "-- Stratagus Map Presentation\n" +
                   "-- File generated by the Stratagus v3.5.4 built-in map editor.\n\n";
        }

        public static string PlayerTypes2P(string[] players)
        {
            return $"DefinePlayerTypes(\"{players[0]}\", \"{players[1]}\")\n";
        }

        public static string PlayerTypes3P(string[] players)
        {
            return $"DefinePlayerTypes(\"{players[0]}\", \"{players[1]}\",  \"{players[2]}\")\n";
        }

        public static string PresentMap(string name, int persons, int width, int height, int smth)
        {
            return $"PresentMap(\"{name}\", {persons}, {width}, {height}, {smth})\n";
        }

        public static string PlayerConfigHeader()
        {
            return "-- player configuration\n";
        }

        public static string PlayerData(int id, Vector2Int view, int lumber, int copper, int stone, string race,
            string faction, string aiType)
        {
            return $"SetStartView({id}, {view.x}, {view.y})\n" +
                   $"SetPlayerData({id}, \"Resources\", \"lumber\", {lumber})\n" +
                   $"SetPlayerData({id}, \"Resources\", \"copper\", {copper})\n" +
                   $"SetPlayerData({id}, \"Resources\", \"stone\", {stone})\n" +
                   $"SetPlayerData({id}, \"RaceName\", \"{race}\")\n" +
                   $"SetPlayerData({id}, \"Faction\", \"{faction}\")\n" +
                   $"SetAiType({id}, \"{aiType}\")\n";
        }

        public static string PlayerData(int id, Vector2Int view, int lumber, int copper, int stone, string race,
            string aiType)
        {
            return $"SetStartView({id}, {view.x}, {view.y})\n" +
                   $"SetPlayerData({id}, \"Resources\", \"lumber\", {lumber})\n" +
                   $"SetPlayerData({id}, \"Resources\", \"copper\", {copper})\n" +
                   $"SetPlayerData({id}, \"Resources\", \"stone\", {stone})\n" +
                   $"SetPlayerData({id}, \"RaceName\", \"{race}\")\n" +
                   $"SetAiType({id}, \"{aiType}\")\n";
        }

        public static string LoadTileset(string tileset)
        {
            return "-- load tilesets\n" +
                   $"LoadTileModels(\"{tileset}\")\n\n";
        }

        public static string GetTerrainTileString(string type, int x, int y, int resAmount, int uid)
        {
            return $"SetTileTerrain(\"{type}\", {x}, {y}, {resAmount}, {uid})\n";
        }

        public static string CreateUnit(string type, int uid, Vector2Int pos)
        {
            return $"unit = CreateUnit(\"{type}\", {uid}, {{{pos.x}, {pos.y}}})\n";
        }

        public static string CreateResource(string type, int uid, Vector2Int pos, int amount)
        {
            return $"unit = CreateUnit(\"{type}\", {uid}, {{{pos.x}, {pos.y}}})\n" +
                   $"SetResourcesHeld(unit, {amount})\n";
        }
    }
}